services:
  - type: web_service
    name: monuvista-backend
    env: node
    plan: starter
    branch: main
    root: backend
    buildCommand: npm install
    startCommand: npm start

  - type: web_service
    name: monuvista-frontend
    env: node
    plan: starter
    branch: main
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: VITE_API_URL
        value: https://monuvista-backend.onrender.com
